name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Prepare Git
      uses: actions/checkout@v2
    - name: Setup python 3.8
      with:
        python-version: 3.8
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r starter/requirements.txt
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        cd starter
        pytest