name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Prepare Git
      uses: actions/checkout@v2
    - name: Configure Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        python-version: 3.8
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        cd starter
        pytest